# Sleep and Dream Database

This dataset is a compilation of various dream report surveys covering a wide range of contexts.

**Source:** CSV file downloaded from [Sleep and Dream Database](https://sleepanddreamdatabase.org) and uploaded to a [Zenodo archive](https://doi.org/10.5281/zenodo.18076716) for stability.

There are many assertion checks before cleaning steps, because I am not sure of the consistency over time with downloads and the format of the raw data file that gets downloaded from the SDDb `Export CSV` option.

The Sleep and Dream Database is only accessible as a complete CSV download through the browser (have to click a button to download). So the file was manually downloaded and uploaded to a [Zenodo archive](https://zenodo.org/records/18076716) for permanence and command line access.

## Setup

Load Python packages and set [pandas](https://github.com/pandas-dev/pandas) display options.

In [1]:
import re
import os
import uuid
from datetime import datetime, timezone

import pandas as pd
import pooch

from IPython.display import display

In [2]:
pd.set_option("display.precision", 2)

## Load source data

### Download source data

Use [pooch](https://github.com/fatiando/pooch) to download and cache the file.

In [3]:
DOWNLOAD_URL = "https://zenodo.org/records/18076716/files/dream_search_2025-12-28T15_50_30.592Z.csv?download=1"
KNOWN_HASH = "md5:4ecfb8cd2a83eabe75d2b6537ca846b6"
CACHE_DIR = pooch.os_cache("pooch").joinpath("sddb")
fname = pooch.retrieve(url=DOWNLOAD_URL, known_hash=KNOWN_HASH, path=CACHE_DIR)

### Read the source data

Use [pandas](https://github.com/pandas-dev/pandas) to read the file.

In [4]:
df = pd.read_csv(fname, parse_dates=["Dream Date"], encoding="utf-8")

### Snapshot

Before any checks or processing, take quick snapshot of what the original dataframe looks like.

View summary info. Take note of shape, data types, and null counts.

In [5]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44556 entries, 0 to 44555
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   Dream Report ID  44556 non-null  object        
 1   Title            0 non-null      float64       
 2   Dream Text       42989 non-null  object        
 3   Participant ID   44412 non-null  object        
 4   Gender           0 non-null      float64       
 5   Age              0 non-null      float64       
 6   Word Count       44556 non-null  int64         
 7   Dream Date       44556 non-null  datetime64[ns]
 8   Survey Name      44556 non-null  object        
 9   Survey ID        44556 non-null  object        
 10  Question         44556 non-null  object        
 11  Categories       0 non-null      float64       
dtypes: datetime64[ns](1), float64(4), int64(1), object(6)
memory usage: 48.6 MB


View descriptive stats for continuous values.

In [6]:
continuous_descriptives = df.describe(exclude="object")
continuous_descriptives.loc["mean", "Dream Date"] = continuous_descriptives.loc["mean", "Dream Date"].round("s")
continuous_descriptives = continuous_descriptives.convert_dtypes(
    infer_objects=False,
    convert_string=False,
    convert_boolean=False,
    convert_integer=True,
    convert_floating=True,
)
display(continuous_descriptives)

Title  Gender   Age  Word Count           Dream Date  Categories
count      0       0     0     44556.0                44556           0
mean    <NA>    <NA>  <NA>      100.73  2012-09-06 14:04:33        <NA>
min     <NA>    <NA>  <NA>         0.0  1968-03-24 00:00:00        <NA>
25%     <NA>    <NA>  <NA>        12.0  2011-04-01 00:00:00        <NA>
50%     <NA>    <NA>  <NA>        55.0  2012-12-31 00:00:00        <NA>
75%     <NA>    <NA>  <NA>       121.0  2015-10-15 00:00:00        <NA>
max     <NA>    <NA>  <NA>      2681.0  2024-12-25 00:00:00        <NA>
std     <NA>    <NA>  <NA>      157.78                  NaN        <NA>

View descriptive stats for object values.

In [7]:
object_descriptives = df.describe(include="object")
display(object_descriptives)

Dream Report ID Dream Text Participant ID  \
count                                  44556      42989          44412   
unique                                 44556      38055          15880   
top     0192a1a8-b8b4-7cef-9f50-520dc2d4e4a4       none         Melvin   
freq                                       1       2644           5204   

                    Survey Name                             Survey ID  \
count                     44556                                 44556   
unique                       85                                    85   
top     2012 Demographic Survey  974766ff-8421-11ea-b97a-0242ac120005   
freq                       6756                                  6756   

                              Question  
count                            44556  
unique                              37  
top     Dream Text: Last Night's Dream  
freq                             12917

View the the first few dataframe rows.

In [8]:
display(df.head())

Dream Report ID  Title  \
0  0192a1a8-b8b4-7cef-9f50-520dc2d4e4a4    NaN   
1  0192a1a8-b8b4-7cef-9f50-520dc2f55d92    NaN   
2  0192a1a8-b8b4-7cef-9f50-520dc317f5c7    NaN   
3  0192a1a8-b8b4-7cef-9f50-520dc33a777a    NaN   
4  0192a1a8-b8b4-7cef-9f50-520dc368d951    NaN   

                                          Dream Text Participant ID  Gender  \
0  Mostly forgotten. Flying across an extensive p...         Melvin     NaN   
1  Beginning forgotten. An alternative school cla...         Melvin     NaN   
2  A lot of Mexican, Hispanic, boys. A school sit...         Melvin     NaN   
3  Danny. Before this there was a long bit, mostl...         Melvin     NaN   
4  North side of Queen Sarah Johnson. Not so much...         Melvin     NaN   

   Age  Word Count Dream Date    Survey Name  \
0  NaN          78 2022-12-04  melvin-dreams   
1  NaN         329 2022-12-07  melvin-dreams   
2  NaN         128 2022-12-07  melvin-dreams   
3  NaN         291 2022-12-08  melvin-dreams   
4  NaN         518 2022-12-09  melvin-dreams   

                              Survey ID            Question  Categories  
0  0192a1a8-b862-73e6-91fd-bb6a7b2e39c8  Last Night's Dream         NaN  
1  0192a1a8-b862-73e6-91fd-bb6a7b2e39c8  Last Night's Dream         NaN  
2  0192a1a8-b862-73e6-91fd-bb6a7b2e39c8  Last Night's Dream         NaN  
3  0192a1a8-b862-73e6-91fd-bb6a7b2e39c8  Last Night's Dream         NaN  
4  0192a1a8-b862-73e6-91fd-bb6a7b2e39c8  Last Night's Dream         NaN

## Checks and Changes

Investigate the dataframe wholistically and then each column independently, performing logical adjustments along the way.

### Check for empty columns

Based on snapshot above, we can see there are a few empty columns. Those can be removed.

In [9]:
empty_columns = df.columns[df.isna().all()].tolist()
df = df.dropna(how="all", axis="columns")
print(f"Dropped {len(empty_columns)} empty columns: {empty_columns}")

Dropped 4 empty columns: ['Title', 'Gender', 'Age', 'Categories']


### Check for constant columns

While not strictly disallowed, columns with a constant value are typically unnecessary.

In [10]:
assert df.nunique().ne(1).all()
print("Verified no constant columns.")

Verified no constant columns.


### Sort column order

Reorder in sensible direction, mostly for easier reading and interpreting printouts that will follow.

In [11]:
COLUMN_ORDER = [
    "Survey ID",
    "Survey Name",
    "Participant ID",
    "Question",
    "Dream Report ID",
    "Word Count",
    "Dream Date",
    "Dream Text",
]
assert df.columns.symmetric_difference(COLUMN_ORDER).empty, "Current and future columns should match"
df = df.reindex(columns=COLUMN_ORDER)

### Investigate `Survey ID` column

I think `Survey ID` is a unique identifier that serves the same function as `Survey Name`.

In [12]:
def is_valid_uuid(uuid_string):
    try:
        uuid_obj = uuid.UUID(uuid_string)
        return str(uuid_obj) == uuid_string
    except ValueError:
        return False

In [13]:
assert df["Survey ID"].apply(is_valid_uuid).all()
assert df["Survey ID"].nunique() == df["Survey Name"].nunique()
assert df.groupby("Survey ID")["Survey Name"].nunique().eq(1).all()
assert df.groupby("Survey Name")["Survey ID"].nunique().eq(1).all()

Since that's true, we can drop the `Survey ID` column.

In [14]:
df = df.drop(columns=["Survey ID"])

### Investigate `Dream ID` column

I think it's a unique dream report identifier, just like `Survey ID` is to surveys.

In [15]:
assert df["Dream Report ID"].apply(is_valid_uuid).all()
assert df["Dream Report ID"].is_unique

Given that each dream report is on its own row, this value is not particularly valuable for us, so we can remove it.

In [16]:
df = df.drop(columns=["Dream Report ID"])

### Investigate `Dream Date` column

I'm not sure if Dream Date is the date of the dream or the date of the data upload, or anything else. It's hard to imagine having a true timestamp date for all dreams in the dataset, but we should check out the column to see if any clues pop out.

First calculate some summary statistics on the dates for each dataset and view as a long table.

In [17]:
dates = (
    df.groupby("Survey Name")["Dream Date"]
    .agg(["size", "count", "nunique", "min", "max", "mean"])
    .sort_values(["nunique", "count"], ascending=False)
    .assign(mean=lambda d: d["mean"].dt.round("d"))
)
with pd.option_context("display.max_rows", None):
    display(dates)

size  count  nunique  \
Survey Name                                                             
melvin-dreams                                    5204   5204     3182   
Palliative Care Dreams 2011                       101    101       59   
Barack Obama Dreams 2008                          100    100       32   
Hillary Clinton Dreams 2008                       100    100       32   
Chartres Journals                                 263    263       23   
Historical Dreams                                  24     24        7   
Krippner International Collection 1990-2005      1436   1436        4   
Film-Related Dreams                                15     15        4   
AD Journals: Lola, Paul, Sophia, Will 2006-2007   449    449        3   
Anthropological Dreams                              6      6        3   
Nepal Dreams 2014                                 535    535        2   
African Church Dreams A                            34     34        2   
Anna Kingsford Journal 1876-1887                   25     25        2   
2012 Demographic Survey                          6756   6756        1   
Online Dreams 2015                               5904   5904        1   
2010 Demographic Survey                          3158   3158        1   
2013 Demographic Survey Winter                   2051   2051        1   
2011 Memorable Dream Survey                      2044   2044        1   
2013 Demographic Survey Summer                   2029   2029        1   
2011 Children's Dream Survey                     1199   1199        1   
Lucille Journal 1998-2018                        1009   1009        1   
Santa Clara Dreams 2012                           811    811        1   
Tanya Journal 2003-2013                           563    563        1   
Hall & Van de Castle Male Norms 1947-1950         491    491        1   
Hall & Van de Castle Female Norms 1947-1950       490    490        1   
Dreamboard Nightmares 2014                        478    478        1   
Mehinaku of Brazil Dreams 1970's                  383    383        1   
Santa Clara Dreams 2008                           370    370        1   
KB Journal 2020                                   366    366        1   
KB Journal 2019a                                  363    363        1   
2021 Sports Dreams Survey                         349    349        1   
Jasmine Journal A                                 333    333        1   
Vera Journal 2020                                 320    320        1   
KM Journal 2015                                   292    292        1   
Melvin Journal 2020                               284    284        1   
Ana Journal 2020                                  258    258        1   
Beverly Journal 1986                              253    253        1   
Beverly Journal 1996                              253    253        1   
Barb Sanders baseline 250                         250    250        1   
Beverly Journal 2006                              247    247        1   
2020 Pandemic May Survey                          238    238        1   
Freya Journal 2020                                234    234        1   
Natural Scientist Journal 1939                    234    234        1   
Lucid Dreams Collection 2010                      226    226        1   
Jasmine Journal B                                 224    224        1   
Bea Journal 2003-2005                             223    223        1   
2020 Racial Justice Survey                        222    222        1   
Rose Journal 2020                                 215    215        1   
Lawrence Journal 2011                             206    206        1   
KB Journal 2012                                   201    201        1   
Trump Dreams 2016-2017                            199    199        1   
Beverly Journal 2016                              187    187        1   
Miami Lab Dreams 1963-1965                        187    187        1   
Myoe Shonin Journal 13th century C

A few things pop out to me:

* The date values are all constant within most datasets (see how min, max, and mean are all the same for most rows). So it's definitely not the date of the dream, but more likely the date of upload.
* The dates in the Survey Name do not always correspond to the Dream Date (e.g., Rosa Journal 2020 is dated in 2021, or more jarringly, Lucrecia de Leon Journal 1590 is dates 2021).
* BUT some of the dates _are_ old and too old to be the date of upload (e.g., Freya Journal 1981-2019 is dated 1981).

Based on the above observations, and the lack of consistency of what the dates probably represent, I'm dropping the `Dream Date` column.

In [18]:
df = df.drop(columns=["Dream Date"])

### Investigate `Word Count` column

I don't think it's very important to keep this column around. In general, I avoid keeping columns with derivative values (i.e., those that can be calculated from other columns). I think this is especially true for word count, because people can use different approaches for calculating this. I.e., they might want to count their own.

But before removing, we should check that the values are sensible in the first place. I've seen in other datasets where the word counts are completely off, and this could potentially reveal bigger issues with the dataset if true.

In [19]:
wc_calculated = df["Dream Text"].str.split().str.len().fillna(0).astype(int)
wc_sddb = df["Word Count"]
wc_diffs = (wc_sddb - wc_calculated)

display(wc_diffs.value_counts().sort_index().rename_axis("WC diff").reset_index())

WC diff  count
0        0  43003
1        1   1553

Most word counts are exactly the same, and having 1553 that have a difference of only 1 is probably fine, but we can look into it.

My suspicion is that is has to do with the rows that have no dream text.

In [20]:
print(f"{'Number of reports SDDb calculated as having 0 word count:':<60} {wc_sddb.eq(0).sum()}")
print(f"{'Number of reports I calculated as having 0 word count:':<60} {wc_calculated.eq(0).sum()}")

Number of reports SDDb calculated as having 0 word count:    14
Number of reports I calculated as having 0 word count:       1567


Suspicious indeed...

In [21]:
print(f"{'Number of reports that have mismatched word counts:':<80} {wc_diffs.ne(0).sum()}")
print(f"{'Number of reports that I calculated as having 0 word count but SDDb did not:':<80} {wc_calculated.eq(0).sum() - wc_sddb.eq(0).sum()}")

Number of reports that have mismatched word counts:                              1553
Number of reports that I calculated as having 0 word count but SDDb did not:     1553


Confirms suspicion. One last check...

In [22]:
empty_reports = df[df["Dream Text"].isna()][["Word Count", "Dream Text"]]
print("WC differences for empty reports only:")
display(empty_reports["Word Count"].value_counts().rename_axis("WC diff").reset_index())
print("First 5 rows with empty reports showing SDDb-calculated WC:")
display(empty_reports.head())

WC differences for empty reports only:


WC diff  count
0        1   1553
1        0     14

First 5 rows with empty reports showing SDDb-calculated WC:


Word Count Dream Text
21096           1        NaN
21219           1        NaN
21308           0        NaN
21317           1        NaN
21429           1        NaN

That verifies that SDDb provides an accurate word count of `0` for only 14 out of 1567 empty dream reports. For all others they provide a word count of `1`. (Note also that there are other reports that are _actually_ one word, so we can't replace the 1s with 0s.)

To me this doesn't raise any red flags about the dream reports themselves, so we can just remove the `Word Count` column and move on.

In [23]:
df = df.drop(columns=["Word Count"])

### Investigate `Question` column

This is potentially a **highly** valuable column, as it appears to indicate what type of question or probe was asked to the dreamer before giving the report. This is not straight-forward to categorize for all dream reports in all different contexts, but I would be happy with anything sensible here.

In [24]:
# First confirm there are no empty values
assert not df["Question"].isna().any()

Get a broad overview of how many different values there are.

In [25]:
display(df["Question"].value_counts().reset_index())

Question  count
0          Dream Text: Last Night's Dream  12917
1           Dream Text: Most Recent Dream   7070
2                      Last Night's Dream   6782
3              Dream Text: Most Memorable   3261
4                  Dream Text: Visitation   2252
5                        Dream Text: Work   2252
6                   Dream Text: Awareness   2252
7                       last_nights_dream   1768
8             Dream Text: Worst Nightmare   1211
9   Dream Text: Earliest Remembered Dream   1017
10                 Dream text: Nightmares    485
11                  Pandemic Dream Report    383
12                      Dream Text: SCU 1    370
13                           LSD_q3_open1    349
14          Dream Text: Significant Dream    227
15                       gackenback:lucid    226
16                         Protest Dreams    222
17                     last_nights_dream2    208
18                     last_nights_dream1    207
19       Dream Text: Last Night's Dream 1    205
20       Dream Text: Last Night's Dream 2    200
21            Dream Text: Spiritual Dream    144
22               Dream Text: Barack Obama    100
23            Dream Text: Hillary Clinton    100
24       Dream Text: Last Night's Dream 3     79
25                     last_nights_dream3     70
26        Dream Text: Non-Spiritual Dream     62
27       Dream Text: Last Night's Dream 4     44
28       Dream Text: Last Night's Dream 5     24
29                     last_nights_dream4     20
30           Dream Text: Memorable Dreams     15
31       Dream Text: Last Night's Dream 6      8
32           Dream Text: Recurring Dreams      7
33                     last_nights_dream5      6
34                   Last Night's Dream 2      6
35       Dream Text: Last Night's Dream 7      4
36                     last_nights_dream6      3

There are a lot of same-but-different values that could be standardized without any controversy. For example, "Dream Text: Last Night's Dream 3" and "last_nights_dream3", or all the variants of Last Night's Dream for that matter.

I think it's fair to:

* Drop the "Dream Text: " prefix from every label
* Drop the "Dream" or "Dreams" or "Dream Report" suffix from every label
* Drop the "s" off of "Worst Nightmares" (technically more accurate for 1 dream report)
* Merge all variants of "Last Night's Dream"
* Merge "Memorable Dreams" and "Most Memorable"

In [26]:
# Remove Dream Text prefix
df["Question"] = df["Question"].str.replace(r"^Dream [Tt]ext:\s*", "", regex=True)

# Remove Dream suffix
df["Question"] = df["Question"].str.replace(r"^(.+) Dream(s)?( Report)?$", r"\1", regex=True)

# Drop the "s" off "Nightmares"
df["Question"] = df["Question"].str.replace(r"^Nightmares$", "Nightmare", regex=True)

# Merge memorable dream labels
df["Question"] = df["Question"].str.replace(r"^Most Memorable$", "Memorable", regex=True)

# Merge last night's dream labels
df["Question"] = df["Question"].str.replace(r"^last_nights_dream\d?$", "Last Night's", regex=True)
df["Question"] = df["Question"].str.replace(r"^Last Night's Dream \d$", "Last Night's", regex=True)

Take another view after replacements.

In [27]:
df["Question"].value_counts(dropna=False).reset_index(drop=False)

Question  count
0          Last Night's  22551
1           Most Recent   7070
2             Memorable   3276
3             Awareness   2252
4            Visitation   2252
5                  Work   2252
6       Worst Nightmare   1211
7   Earliest Remembered   1017
8             Nightmare    485
9              Pandemic    383
10                SCU 1    370
11         LSD_q3_open1    349
12          Significant    227
13     gackenback:lucid    226
14              Protest    222
15            Spiritual    144
16      Hillary Clinton    100
17         Barack Obama    100
18        Non-Spiritual     62
19            Recurring      7

One thing that pops out now is how there are labels for Clinton and Obama dreams but not Trump. This only stands out because I know there is a similar Trump dataset in here that matches the other presidential datasets in many ways. These labels are particularly important for those datasets because I think people were asked to report dreams _about those presidents_, and so we should not treat them as typical dreams. Let's investigate...

First check what the Trump dataset is using for Question values, and show the other presidential datasets alongside for reference. Just view the first few rows from each dataset.

In [28]:
display(
    df[df["Survey Name"].str.contains(r"Trump|Clinton|Obama", regex=True)]
    .groupby("Survey Name")
    .head(n=2)
)

Survey Name        Participant ID         Question  \
9620        Trump Dreams 2016-2017          td2017:td156     Last Night's   
9621        Trump Dreams 2016-2017          td2017:td157     Last Night's   
41816  Hillary Clinton Dreams 2008   dreambank_hilary:99  Hillary Clinton   
41817  Hillary Clinton Dreams 2008  dreambank_hilary:100  Hillary Clinton   
41827     Barack Obama Dreams 2008   dreambank_barack:99     Barack Obama   
41828     Barack Obama Dreams 2008  dreambank_barack:100     Barack Obama   

                                              Dream Text  
9620   I dreamt that I was hosting a party/conference...  
9621   Donald Trump is here. My impression is that I ...  
41816  I am anxiously waiting to hear the results of ...  
41817  Hillary was visiting my family -- which was a ...  
41827  I am in a large room with some high-school fri...  
41828  I'm in Washington, walking past some shallow, ...

But then if the Clinton and Obama datasets use president names for the `Question` value, why does the Trump dataset use "Last Night's Dream"? I'm assuming that this is actually also dreams _about Trump_ and not just last night's dream? But we can confirm that by looking at a random sample of dreams from each dataset.

In [29]:
with pd.option_context("display.max_colwidth", 100):
    display(
        df[df["Survey Name"].str.contains(r"Trump|Clinton|Obama", regex=True)]
        .groupby("Survey Name")
        .sample(n=10, random_state=42)
        .drop(columns=["Participant ID", "Question"])
    )

Survey Name  \
41981     Barack Obama Dreams 2008   
41931     Barack Obama Dreams 2008   
41963     Barack Obama Dreams 2008   
41913     Barack Obama Dreams 2008   
41912     Barack Obama Dreams 2008   
41902     Barack Obama Dreams 2008   
41864     Barack Obama Dreams 2008   
41978     Barack Obama Dreams 2008   
41847     Barack Obama Dreams 2008   
41827     Barack Obama Dreams 2008   
41973  Hillary Clinton Dreams 2008   
41885  Hillary Clinton Dreams 2008   
41938  Hillary Clinton Dreams 2008   
41916  Hillary Clinton Dreams 2008   
41836  Hillary Clinton Dreams 2008   
41846  Hillary Clinton Dreams 2008   
42015  Hillary Clinton Dreams 2008   
41856  Hillary Clinton Dreams 2008   
41924  Hillary Clinton Dreams 2008   
41843  Hillary Clinton Dreams 2008   
9794        Trump Dreams 2016-2017   
9653        Trump Dreams 2016-2017   
9690        Trump Dreams 2016-2017   
9787        Trump Dreams 2016-2017   
9720        Trump Dreams 2016-2017   
9702        Trump Dreams 2016-2017   
9707        Trump Dreams 2016-2017   
9727        Trump Dreams 2016-2017   
9761        Trump Dreams 2016-2017   
9807        Trump Dreams 2016-2017   

                                                                                                Dream Text  
41981  I was Barack's mistress. He picked me up from a party that I was at with Alton Brown. We went dr...  
41931  I went to Washington to meet Barack. He was running around and I kept having to run to catch up ...  
41963  My girlfriend and I are hanging out with Barack, leaning against the brick wall of a public scho...  
41913  Barack had come to speak at my summer camp. It was outside at Sunday Service, and we were all si...  
41912  It was Valentine's Day. I was waiting in line at a cheap department store. I was fifth or sith i...  
41902  Barack and I had been involved in what I thought was a serious romantic relationship. Throughout...  
41864  I was shopping at a drugstore and came across a display of Valentine's Day gift ideas. It includ...  
41978           I dreamed last night that I was running towards something and Barack Obama was chasing me.  
41847  I'm standing on a street corner watching Barack enthusiastically help a baby onto a pogo-stick /...  
41827  I am in a large room with some high-school friends, taking a test Barack has designed. Competiti...  
41973  I went up to Hillary Clinton and said, Thank you for running, it means a lot to us. She rolled h...  
41885  So there was a jazz band playing. Hillary was in front of the stage with the mike, trying to be ...  
41938  I slept really hard last night and dreamed that Hillary Clinton became President of the U.S., an...  
41916  I was at a sweet country inn, the type of bed and breakfast that you would escape to for a roman...  
41836  Hillary Clinton is my therapist. We are sitting on a bench overlooking the Mississippi River and...  
41846  Hillary and I went shopping for corned beef in a New York deli. In the dream, I was overwhelmed ...  
42015  I walked into a restaurant and Bill and Hillary were sitting at the bar. At first I didn't reali...  
41856  In my dream I am a super-delegate. I'm sitting at the dining room table filling out the ballot. ...  
41924  Hillary was in our guest bedroom and was putting on one of my wife's cashmere sweaters, a pink o...  
41843  A few days before giving birth, I dreamed I was in the hospital in labor. For some reason, Hilla...  
9794   I am a trump supporter.. maybe more didnt want the alternative the night before the election he ...  
9653   I wasn't going to share this but here it goes... I was at some political/social event and happen...  
9690   I was outside, in Golden Gate Park, with my 10-year old daughter. A group of men and boys were m...  
9787   I am on a date with Donald Trump. We are eating lunch in a restaurant on a film set. We are at t...  
9720   I dreamt I was leaving my pub in my town when a done up flash limo came past with dollar signs a...  
9702   If 

Yes, confirmed that the "Trump Dreams" dataset _does_ ask specifically dreams about Trump, just as the other presidential datasets do.

I feel comfortable replacing the "Last Night's Dream" values in Trump dataset with "Donald Trump" (following the pattern of "Barack Obama" and "Hillary Clinton").

In [30]:
df.loc[df["Survey Name"].eq("Trump Dreams 2016-2017"), "Question"] = "Donald Trump"

However, this does not mean that all other Question values are correct!

The Trump issue makes me worry about other use of "Last Night's Dream" as well. Another consideration is that it is by far the most common value in this column. That could be if it is used for all dream diaries, but it could also mean that this is like a default fill value for any dataset where the Question was not prefilled or is unknown.

I also wonder if "Last Night's Dream" could be merged with "Most Recent Dream"...

Also, there are still a few labels left that I can't make sense of but can leave in for now, namely "SCU 1" and "LSD_q3_open1".

I'm also curious what kind of variability there is in the Question label for different datasets.

Let's view the Question values grouped by dataset.

In [31]:
display(df.groupby("Survey Name")["Question"].value_counts().reset_index())

Survey Name             Question  count
0         2010 Demographic Survey      Worst Nightmare   1211
1         2010 Demographic Survey  Earliest Remembered   1016
2         2010 Demographic Survey          Most Recent    931
3    2011 Children's Dream Survey            Memorable   1199
4     2011 Memorable Dream Survey            Memorable   2044
..                            ...                  ...    ...
96              Tita Journal 2020         Last Night's     48
97         Trump Dreams 2016-2017         Donald Trump    199
98              Vera Journal 2020         Last Night's    320
99   Wolfgang Pauli dreams 1930's         Last Night's     58
100                 melvin-dreams         Last Night's   5204

[101 rows x 3 columns]

Based on that quick look, it's clear that there are multiple questions within some datasets, probably a situation where a participant was asked to report multiple dreams, but not sure yet.

### Investigate `Participant ID` column

Ideally this is a clear indicator _within datasets_ of different participants. But in my experience this can get messy within larger collections or meta-datasets like this one. There are a few ways to investigate this.

First, I noticed in the initial snapshot of source data that there are a few missing values.

In [32]:
display(
    df[df["Participant ID"].isna()]["Survey Name"].value_counts().reset_index(name="n_missing")
)

Survey Name  n_missing
0  Aristides Journal 2nd century CE        120
1  Anna Kingsford Journal 1876-1887         24

Only 2 datasets have missing values. But are they _all_ missing or just a subset?

In [33]:
datasets_with_missing_participant_ids = df.loc[df["Participant ID"].isna(), "Survey Name"].unique()
display(
    df
    .groupby("Survey Name")
    ["Participant ID"].value_counts(dropna=False)
    .loc[datasets_with_missing_participant_ids]
    .reset_index()
)

Survey Name                        Participant ID  \
0  Aristides Journal 2nd century CE                                   NaN   
1  Aristides Journal 2nd century CE                   P. Aelius Aristides   
2  Anna Kingsford Journal 1876-1887                                   NaN   
3  Anna Kingsford Journal 1876-1887  anna_kingsford_series:anna_kingsford   

   count  
0    120  
1      1  
2     24  
3      1

Thankfully there is correct 1 value for "Participant ID" in both these datasets. So we can use that value to front/back fill the empty values with the proper value.

In [34]:
print("Number of Participant ID NaN values before correction:", df["Participant ID"].isna().sum())
for ds in datasets_with_missing_participant_ids:
    assert df.loc[df["Survey Name"].eq(ds), "Participant ID"].isna().any()
    assert not df.loc[df["Survey Name"].eq(ds), "Participant ID"].isna().all()
    df.loc[df["Survey Name"].eq(ds), "Participant ID"] = df.loc[df["Survey Name"].eq(ds), "Participant ID"].bfill().ffill()
print("Number of Participant ID NaN values after correction:", df["Participant ID"].isna().sum())

Number of Participant ID NaN values before correction: 144
Number of Participant ID NaN values after correction: 0


With that solved (no empty values), let's take a bigger look at the "Participant ID" column and what values typically look like.

View the 20 most frequent Participant IDs.

In [35]:
display(df["Participant ID"].value_counts(dropna=False).head(n=20).reset_index())

Participant ID  count
0                                        Melvin   5204
1                                       Lucille   1009
2                                            KB    729
3                                  tanya1:tanya    563
4                      jasmine_journala:jasmine    333
5                                          Vera    320
6                                     km2015:km    292
7                                bea_series:bea    286
8                            2020_dreams:melvin    284
9                       recent_dreams_2015:4688    268
10                                          Ana    258
11                         beverly_1986:beverly    253
12                         beverly_1996:beverly    253
13                          bs_250:barb_sanders    250
14                         beverly_2006:beverly    247
15  natural_scientist_journal:natural_scientist    234
16                            2020_dreams:freya    234
17                     jasmine_journalb:jasmine    224
18                                         Rose    215
19                      recent_dreams_2015:7361    213

And 10 of the least frequent.

In [36]:
display(df["Participant ID"].value_counts(dropna=False).tail(n=10).reset_index())

Participant ID  count
0   dreambank_hilary:9      1
1  harris_2013s:003180      1
2         Respondent21      1
3         Respondent19      1
4         Respondent17      1
5  harris_2013s:003179      1
6  harris_2013s:003122      1
7  harris_2013s:003119      1
8  harris_2013s:003118      1
9   harris_2011:025126      1

Now, a more valuable view is what Participant ID values look like in relation to Survey ID.

This can tell us if participant IDs are unique within a dataset, and provide an intuition of how many reports there are per participant ID. From that you also can infer from a quick glance how much of the datasets are dream diaries (those with 1 unique participant ID).

In [37]:
n_authors_per_survey = (
    df
    .groupby("Survey Name")["Participant ID"]
    .agg(["count", "nunique", lambda x: x.duplicated().sum(), lambda x: x.isna().sum()])
    .assign(all_authors_unique=lambda d: d["count"].eq(d["nunique"]))
    .rename(columns={"<lambda_0>": "duplicates", "<lambda_1>": "isna"})
    .rename_axis(columns="Participant ID column")
    .sort_values(["count", "nunique"], ascending=False)
)
with pd.option_context("display.max_rows", None):
    display(n_authors_per_survey)

Participant ID column                            count  nunique  duplicates  \
Survey Name                                                                   
2012 Demographic Survey                           6756     2252        4504   
Online Dreams 2015                                5904       81        5823   
melvin-dreams                                     5204        1        5203   
2010 Demographic Survey                           3158     1716        1442   
2013 Demographic Survey Winter                    2051     2051           0   
2011 Memorable Dream Survey                       2044     2044           0   
2013 Demographic Survey Summer                    2029     2029           0   
Krippner International Collection 1990-2005       1436     1436           0   
2011 Children's Dream Survey                      1199     1199           0   
Lucille Journal 1998-2018                         1009        1        1008   
Santa Clara Dreams 2012                            811      144         667   
Tanya Journal 2003-2013                            563        1         562   
Nepal Dreams 2014                                  535      237         298   
Hall & Van de Castle Male Norms 1947-1950          491        5         486   
Hall & Van de Castle Female Norms 1947-1950        490        5         485   
Dreamboard Nightmares 2014                         478      478           0   
AD Journals: Lola, Paul, Sophia, Will 2006-2007    449        4         445   
Mehinaku of Brazil Dreams 1970's                   383       38         345   
Santa Clara Dreams 2008                            370      183         187   
KB Journal 2020                                    366        1         365   
KB Journal 2019a                                   363        1         362   
2021 Sports Dreams Survey                          349      349           0   
Jasmine Journal A                                  333        1         332   
Vera Journal 2020                                  320        1         319   
KM Journal 2015                                    292        1         291   
Melvin Journal 2020                                284        1         283   
Chartres Journals                                  263       94         169   
Ana Journal 2020                                   258        1         257   
Beverly Journal 1986                               253        1         252   
Beverly Journal 1996                               253        1         252   
Barb Sanders baseline 250                          250        1         249   
Beverly Journal 2006                               247        1         246   
2020 Pandemic May Survey                           238      238           0   
Freya Journal 2020                                 234        1         233   
Natural Scientist Journal 1939                     234        1         233   
Lucid Dreams Collection 2010                       226      225           1   
Jasmine Journal B                                  224        1         223   
Bea Journal 2003-2005                              223        1         222   
2020 Racial Justice Survey                         222      222           0   
Rose Journal 2020                                  215        1         214   
Lawrence Journal 2011                              206        1         205   
KB Journal 2012                                    201        1         200   
Trump Dreams 2016-2017                             199      197           2   
Miami Lab Dreams 1963-1965                         187        8         179   
Beverly Journal 2016                               187        1         186   
Myoe Shonin Journal 13th century CE                170        1         169   
Jasmine Journal D                                  148        1         147   
2020 Pandemic April Survey                         145      145           0   
Miami Home Dreams 1964-1965                       

Things that pop out to me:

* Some datasets have huge discrepancies between the number of dreams and the number of participants. For example the "Online Dreams 2015" dataset has 5904 dreams from 81 participants. That's an average of 73 dreams per participant! Not impossible, but unlikely? See also the 2012 and 2012 Demographics Surveys.
* Lots of dream diaries!
* Both Hall & Van de Castle datasets report only 5 unique participant IDs within each dataset. I don't think that's accurate.

But I don't see anything else worth changing, since it would be speculative at this point and I don't know what to change suspicious things _to_.

### Investigate `Dream Text` column

Some key things to investigate:

* The empty (`NaN`) Dream Text cells
* That "none" showed as the most frequent value in the source data snapshot.
* Common issues like extraneous surrounding whitespace or quotations
* My subjective observation of many dream reports that don't appear to be dream reports at all. I think things like "no recall" are acceptable in dream reports, since that might be of value to some even if not technically a dream. But some of these, in particular the Surveys, it seems that people respond with totally unrelated comments.
    - I've noticed that the presidential/political dream reports are occasionally filled with political views that do not relate to a dream.
    - I've noticed that there are some responses akin to stuff like "I'm not going to respond".
* My subjective observation that there are many duplicated dream reports, sometimes from the same participant, other times from different participants.

Let's look at all these things in detail and apply changes were defendable.

#### The empty dream reports

There is an easy answer to empty dream reports: remove them. But before doing so, take a quick look to see where most of them are coming from.

In [38]:
print(f"Number of empty dream reports: {df['Dream Text'].isna().sum()}")

Number of empty dream reports: 1567


In [39]:
display(
    df.groupby(["Survey Name"])["Dream Text"]
    .agg(["size", lambda x: x.isna().sum()])
    .rename(columns={"size": "n_rows", "<lambda_0>": "n_missing"})
    .assign(pct_missing=lambda df: df["n_missing"] / df["n_rows"] * 100)
    .reindex(columns=["pct_missing", "n_rows", "n_missing"])
    .sort_values("pct_missing", ascending=False)
    .assign(pct_missing=lambda d: d["pct_missing"].apply(lambda x: f"{x:.1f}%"))
    .query("n_missing > 0")
)

pct_missing  n_rows  n_missing
Survey Name                                                  
2012 Demographic Survey              20.0%    6756       1351
Santa Clara Dreams 2008               4.1%     370         15
2011 Memorable Dream Survey           3.6%    2044         74
2013 Demographic Survey Winter        2.9%    2051         59
2011 Children's Dream Survey          2.0%    1199         24
2013 Demographic Survey Summer        1.3%    2029         27
2010 Demographic Survey               0.5%    3158         16
Lucid Dreams Collection 2010          0.4%     226          1

Same thing but with a subgroup of Question

In [40]:
display(
    df.groupby(["Survey Name", "Question"])["Dream Text"]
    .agg(["size", lambda x: x.isna().sum()])
    .rename(columns={"size": "n_rows", "<lambda_0>": "n_missing"})
    .assign(pct_missing=lambda df: df["n_missing"] / df["n_rows"] * 100)
    .reindex(columns=["pct_missing", "n_rows", "n_missing"])
    .assign(pct_missing=lambda d: d["pct_missing"].apply(lambda x: f"{x:.1f}%"))
    .query("n_missing > 0")
    .sort_index()
)

pct_missing  n_rows  \
Survey Name                    Question                                  
2010 Demographic Survey        Earliest Remembered        0.6%    1016   
                               Most Recent                0.5%     931   
                               Worst Nightmare            0.4%    1211   
2011 Children's Dream Survey   Memorable                  2.0%    1199   
2011 Memorable Dream Survey    Memorable                  3.6%    2044   
2012 Demographic Survey        Awareness                 20.2%    2252   
                               Visitation                19.8%    2252   
                               Work                      20.0%    2252   
2013 Demographic Survey Summer Most Recent                1.3%    2029   
2013 Demographic Survey Winter Most Recent                2.9%    2051   
Lucid Dreams Collection 2010   gackenback:lucid           0.4%     226   
Santa Clara Dreams 2008        SCU 1                      4.1%     370   

                                                    n_missing  
Survey Name                    Question                        
2010 Demographic Survey        Earliest Remembered          6  
                               Most Recent                  5  
                               Worst Nightmare              5  
2011 Children's Dream Survey   Memorable                   24  
2011 Memorable Dream Survey    Memorable                   74  
2012 Demographic Survey        Awareness                  454  
                               Visitation                 446  
                               Work                       451  
2013 Demographic Survey Summer Most Recent                 27  
2013 Demographic Survey Winter Most Recent                 59  
Lucid Dreams Collection 2010   gackenback:lucid             1  
Santa Clara Dreams 2008        SCU 1                       15

Now that we have a good idea of what we are removing, we can remove them.

In [41]:
df = df.dropna(subset=["Dream Text"])

#### Other potentially "empty" cells

Motivated by the observation of a high frequency of "none" values, and other little things, I want to explore other possibilities of dream reports that are functionally _empty_ despite having text or other values in them.

It is also tough to know what to do with things like "none", as they might be no recall. I think the context matters a lot, like in a lab study "none" might count for something, but in a demographic survey I would probably not want to keep it. Does that mean someone never had a dream about Obama? That might be useful, I just don't know if I can be confident that they are saying that, versus just spamming the text box. Given my much lower motivation to run analyses on recall/no-recall, especially in those types of datasets, I think I'm more inclined to remove them.

In [42]:
print(f"{'Number of dream reports = empty/NaN':.<60}{df["Dream Text"].isna().sum()}")
print(f"{'Number of dream reports = NoneType':.<60}{(df["Dream Text"] == None).sum()}")
print(f"{'Number of dream reports = \'\'':.<60}{(df["Dream Text"] == "").sum()}")
print(f"{'Number of dream reports = \'none\'':.<60}{(df["Dream Text"] == "none").sum()}")
print(f"{'Number of dream reports = \'none.\'':.<60}{(df["Dream Text"] == "none.").sum()}")
print(f"{'Number of dream reports = \'None\'':.<60}{(df["Dream Text"] == "None").sum()}")
print(f"{'Number of dream reports = \'None.\'':.<60}{(df["Dream Text"] == "None.").sum()}")
print(f"{'Number of dream reports = \'nothing\'':.<60}{(df["Dream Text"] == "nothing").sum()}")
print(f"{'Number of dream reports = \'nothing.\'':.<60}{(df["Dream Text"] == "nothing.").sum()}")
print(f"{'Number of dream reports = \'Nothing\'':.<60}{(df["Dream Text"] == "Nothing").sum()}")
print(f"{'Number of dream reports = \'Nothing.\'':.<60}{(df["Dream Text"] == "Nothing.").sum()}")

Number of dream reports = empty/NaN.........................0
Number of dream reports = NoneType..........................0
Number of dream reports = ''................................0
Number of dream reports = 'none'............................2644
Number of dream reports = 'none.'...........................3
Number of dream reports = 'None'............................0
Number of dream reports = 'None.'...........................31
Number of dream reports = 'nothing'.........................21
Number of dream reports = 'nothing.'........................0
Number of dream reports = 'Nothing'.........................4
Number of dream reports = 'Nothing.'........................0


This is kind of inconclusive to me. I mean it's clear that there exists a variety of related values, suggesting that SDDb did not use "none" as a kind of default filler for empty values in some datasets, but at the same time, the number of "none" is _so_ much higher than all the others that it's also possible it was used to fill empty values. Or also likely a combination where some people are just responding that way and others are filled. I don't know.

Let's take a look more broadly at one-word dream reports.

In [43]:
display(df[df["Dream Text"].str.split().str.len().eq(1)])

Survey Name     Participant ID             Question  \
328              melvin-dreams             Melvin         Last Night's   
340              melvin-dreams             Melvin         Last Night's   
363              melvin-dreams             Melvin         Last Night's   
377              melvin-dreams             Melvin         Last Night's   
396              melvin-dreams             Melvin         Last Night's   
...                        ...                ...                  ...   
41405  2010 Demographic Survey  zogby_052110:3080  Earliest Remembered   
41415  2010 Demographic Survey  zogby_052110:2880          Most Recent   
41424  2010 Demographic Survey  zogby_052110:2880  Earliest Remembered   
41465  2010 Demographic Survey  zogby_052110:1310  Earliest Remembered   
41491  2010 Demographic Survey    zogby_052110:15      Worst Nightmare   

      Dream Text  
328         Mary  
340      Seattle  
363         Mary  
377      Flying?  
396         Mary  
...          ...  
41405   FLOATINH  
41415         no  
41424         no  
41465    Falling  
41491    Refused  

[4176 rows x 4 columns]

Over 4000 dreams with one word! That's just under 10% of the dataset!

Some of the 1-word dreams are probably worth keeping, like in the "melvin-dreams" dataset.

And in the "2010 Demographic Survey", "Falling" is acceptable to me, but "no" is not, nor is "Refused".

Note this also includes 1-character length reports!

In [44]:
display(df[df["Dream Text"].str.len().eq(1)])

Survey Name         Participant ID         Question  \
8109       2020 Pandemic April Survey  2020pandemicapril:257         Pandemic   
8123       2020 Pandemic April Survey   2020pandemicapril:60         Pandemic   
8124       2020 Pandemic April Survey   2020pandemicapril:34         Pandemic   
21307  2013 Demographic Survey Summer    harris_2013s:002958      Most Recent   
21324  2013 Demographic Survey Summer    harris_2013s:002950      Most Recent   
...                               ...                    ...              ...   
37495     2011 Memorable Dream Survey     harris_2011:003600        Memorable   
37521     2011 Memorable Dream Survey     harris_2011:003226        Memorable   
38455         2010 Demographic Survey     zogby_052110:48690  Worst Nightmare   
38686         2010 Demographic Survey     zogby_052110:45347  Worst Nightmare   
40462         2010 Demographic Survey     zogby_052110:26631  Worst Nightmare   

      Dream Text  
8109           ,  
8123           .  
8124           .  
21307          -  
21324          C  
...          ...  
37495          f  
37521          .  
38455          .  
38686          .  
40462          0  

[68 rows x 4 columns]

To me, those should definitely be removed.

View the first few single-character reports from all datasets where they are present, to get a feel for what the text looks like and which datasets they are in.

In [45]:
display(df[df["Dream Text"].str.len().eq(1)].groupby("Survey Name").head(n=3))

Survey Name          Participant ID  \
8109       2020 Pandemic April Survey   2020pandemicapril:257   
8123       2020 Pandemic April Survey    2020pandemicapril:60   
8124       2020 Pandemic April Survey    2020pandemicapril:34   
21307  2013 Demographic Survey Summer     harris_2013s:002958   
21324  2013 Demographic Survey Summer     harris_2013s:002950   
21340  2013 Demographic Survey Summer     harris_2013s:002939   
24610  2013 Demographic Survey Winter     harris_2013w:004104   
24637  2013 Demographic Survey Winter     harris_2013w:004150   
24777  2013 Demographic Survey Winter     harris_2013w:004399   
31095         2012 Demographic Survey      harris_2012:002456   
32237         2012 Demographic Survey      harris_2012:002891   
32238         2012 Demographic Survey      harris_2012:002891   
34512    2011 Children's Dream Survey  harris_youth_2011:5658   
34521    2011 Children's Dream Survey  harris_youth_2011:5367   
34673    2011 Children's Dream Survey  harris_youth_2011:9233   
35703     2011 Memorable Dream Survey      harris_2011:066415   
35842     2011 Memorable Dream Survey      harris_2011:055422   
35999     2011 Memorable Dream Survey      harris_2011:043742   
38455         2010 Demographic Survey      zogby_052110:48690   
38686         2010 Demographic Survey      zogby_052110:45347   
40462         2010 Demographic Survey      zogby_052110:26631   

              Question Dream Text  
8109          Pandemic          ,  
8123          Pandemic          .  
8124          Pandemic          .  
21307      Most Recent          -  
21324      Most Recent          C  
21340      Most Recent          N  
24610      Most Recent          ?  
24637      Most Recent          ?  
24777      Most Recent          I  
31095        Awareness          h  
32237             Work          a  
32238        Awareness          a  
34512        Memorable          .  
34521        Memorable          /  
34673        Memorable          n  
35703        Memorable          -  
35842        Memorable          X  
35999        Memorable          .  
38455  Worst Nightmare          .  
38686  Worst Nightmare          .  
40462  Worst Nightmare          0

Get precise single-character counts for each dataset.

In [46]:
display(
    df[df["Dream Text"].str.len().eq(1)]
    .groupby("Survey Name")
    .size()
    .reset_index(name="n_1char_reports")
)

Survey Name  n_1char_reports
0         2010 Demographic Survey                3
1    2011 Children's Dream Survey               13
2     2011 Memorable Dream Survey               15
3         2012 Demographic Survey               10
4  2013 Demographic Survey Summer               10
5  2013 Demographic Survey Winter               14
6      2020 Pandemic April Survey                3

Unsurprisingly these are all coming from Survey datasets.

What about 2 characters?

In [47]:
display(df[df["Dream Text"].str.len().eq(2)].groupby("Survey Name").head(n=3))

Survey Name          Participant ID  \
5577        2021 Sports Dreams Survey   sportsDreams2021:3757   
20904  2013 Demographic Survey Summer     harris_2013s:003459   
20929  2013 Demographic Survey Summer     harris_2013s:003454   
20950  2013 Demographic Survey Summer     harris_2013s:003422   
24401  2013 Demographic Survey Winter     harris_2013w:003665   
24407  2013 Demographic Survey Winter     harris_2013w:003674   
24409  2013 Demographic Survey Winter     harris_2013w:003676   
27456         2012 Demographic Survey      harris_2012:001006   
27457         2012 Demographic Survey      harris_2012:001006   
27469         2012 Demographic Survey      harris_2012:001014   
34444    2011 Children's Dream Survey  harris_youth_2011:2178   
34445    2011 Children's Dream Survey  harris_youth_2011:2167   
34472    2011 Children's Dream Survey  harris_youth_2011:1506   
35646     2011 Memorable Dream Survey      harris_2011:067378   
35683     2011 Memorable Dream Survey      harris_2011:067249   
35754     2011 Memorable Dream Survey      harris_2011:061987   
38570         2010 Demographic Survey      zogby_052110:46998   
38687         2010 Demographic Survey      zogby_052110:45318   
38721         2010 Demographic Survey      zogby_052110:44909   

              Question Dream Text  
5577      LSD_q3_open1         Dk  
20904      Most Recent         na  
20929      Most Recent         na  
20950      Most Recent         no  
24401      Most Recent         Na  
24407      Most Recent         no  
24409      Most Recent         no  
27456        Awareness         ns  
27457       Visitation         pa  
27469       Visitation         no  
34444        Memorable         Na  
34445        Memorable         na  
34472        Memorable         na  
35646        Memorable         no  
35683        Memorable         ok  
35754        Memorable         na  
38570  Worst Nightmare         No  
38687  Worst Nightmare         no  
38721      Most Recent         no

Same datasets. I say remove as well. Three characters?

In [48]:
display(df[df["Dream Text"].str.len().eq(3)].groupby("Survey Name").head(n=3))

Survey Name           Participant ID  \
5477        2021 Sports Dreams Survey    sportsDreams2021:2419   
5623        2021 Sports Dreams Survey    sportsDreams2021:1505   
8266         2020 Pandemic May Survey  2020pandemicsurvey:1415   
21062  2013 Demographic Survey Summer      harris_2013s:003265   
21334  2013 Demographic Survey Summer      harris_2013s:002931   
21438  2013 Demographic Survey Summer      harris_2013s:002809   
24916  2013 Demographic Survey Winter      harris_2013w:004803   
25193  2013 Demographic Survey Winter      harris_2013w:005222   
25285  2013 Demographic Survey Winter      harris_2013w:005322   
27507         2012 Demographic Survey       harris_2012:001030   
27645         2012 Demographic Survey       harris_2012:001081   
27714         2012 Demographic Survey       harris_2012:001114   
34589    2011 Children's Dream Survey   harris_youth_2011:3512   
34821    2011 Children's Dream Survey  harris_youth_2011:14825   
35130    2011 Children's Dream Survey  harris_youth_2011:25987   
35833     2011 Memorable Dream Survey       harris_2011:052509   
36190     2011 Memorable Dream Survey       harris_2011:038494   
36241     2011 Memorable Dream Survey       harris_2011:037534   
38564         2010 Demographic Survey       zogby_052110:46998   
38567         2010 Demographic Survey       zogby_052110:46998   
39277         2010 Demographic Survey       zogby_052110:39586   

                  Question Dream Text  
5477          LSD_q3_open1        Idk  
5623          LSD_q3_open1        IDK  
8266              Pandemic        sad  
21062          Most Recent        Ghe  
21334          Most Recent        wee  
21438          Most Recent        meh  
24916          Most Recent        XYZ  
25193          Most Recent        ...  
25285          Most Recent        tkj  
27507            Awareness        dsf  
27645            Awareness        yes  
27714            Awareness        Yes  
34589            Memorable        cop  
34821            Memorable        unk  
35130            Memorable        Idk  
35833            Memorable        idk  
36190            Memorable        xxx  
36241            Memorable        nha  
38564          Most Recent        No.  
38567  Earliest Remembered        No.  
39277  Earliest Remembered        Pet

Still just demographic surveys. Lots more that is clear grounds for removal, including button mashing and IDK. But we also start to see potential keepers, as 3-characters is now getting into meaningful-word territory (e.g., Pet, cop, sad).

I don't want to remove all these, but glancing at a few like this is helpful to see what else could come out.

Four characters

In [49]:
display(df[df["Dream Text"].str.len().eq(4)].groupby("Survey Name").head(n=3))

Survey Name          Participant ID  \
328                     melvin-dreams                  Melvin   
363                     melvin-dreams                  Melvin   
396                     melvin-dreams                  Melvin   
5625        2021 Sports Dreams Survey    sportsDreams2021:745   
7808       2020 Racial Justice Survey  2020racialjustice:3700   
8358         2020 Pandemic May Survey   2020pandemicsurvey:85   
21003  2013 Demographic Survey Summer     harris_2013s:003359   
21047  2013 Demographic Survey Summer     harris_2013s:003276   
21063  2013 Demographic Survey Summer     harris_2013s:003266   
24363  2013 Demographic Survey Winter     harris_2013w:003586   
24426  2013 Demographic Survey Winter     harris_2013w:003716   
24475  2013 Demographic Survey Winter     harris_2013w:003798   
27455         2012 Demographic Survey      harris_2012:001006   
27459         2012 Demographic Survey      harris_2012:001007   
27460         2012 Demographic Survey      harris_2012:001007   
34446    2011 Children's Dream Survey  harris_youth_2011:2149   
34462    2011 Children's Dream Survey  harris_youth_2011:1650   
34569    2011 Children's Dream Survey  harris_youth_2011:3968   
35717     2011 Memorable Dream Survey      harris_2011:064591   
35723     2011 Memorable Dream Survey      harris_2011:065052   
35742     2011 Memorable Dream Survey      harris_2011:064296   
38355         2010 Demographic Survey      zogby_052110:49537   
38359         2010 Demographic Survey      zogby_052110:49537   
38481         2010 Demographic Survey      zogby_052110:48254   

                  Question Dream Text  
328           Last Night's       Mary  
363           Last Night's       Mary  
396           Last Night's       Mary  
5625          LSD_q3_open1       none  
7808               Protest       love  
8358              Pandemic       love  
21003          Most Recent       none  
21047          Most Recent       Gggg  
21063          Most Recent       none  
24363          Most Recent       none  
24426          Most Recent       none  
24475          Most Recent       none  
27455                 Work       .pop  
27459            Awareness       none  
27460           Visitation       none  
34446            Memorable       none  
34462            Memorable       none  
34569            Memorable       none  
35717            Memorable       none  
35723            Memorable       none  
35742            Memorable       nope  
38355          Most Recent       none  
38359  Earliest Remembered       none  
38481          Most Recent       life

Useful! Melvin starts to pop up, so not just surveys, but more button mashing and lots of none, nope, etc.

In [50]:
display(df[df["Dream Text"].str.len().eq(5)].groupby("Survey Name").head(n=3))

Survey Name                        Participant ID  \
7908       2020 Racial Justice Survey                2020racialjustice:1263   
17390         African Church Dreams B        african_church_dreams2:charles   
21017  2013 Demographic Survey Summer                   harris_2013s:003345   
21104  2013 Demographic Survey Summer                   harris_2013s:003225   
21905  2013 Demographic Survey Summer                   harris_2013s:002239   
24484  2013 Demographic Survey Winter                   harris_2013w:003813   
24496  2013 Demographic Survey Winter                   harris_2013w:003833   
25301  2013 Demographic Survey Winter                   harris_2013w:005339   
27598         2012 Demographic Survey                    harris_2012:001064   
27630         2012 Demographic Survey                    harris_2012:001075   
27719         2012 Demographic Survey                    harris_2012:001117   
34415             Film-Related Dreams  film_dreams:film_dreams:ray_winstone   
34465    2011 Children's Dream Survey                harris_youth_2011:1636   
35062    2011 Children's Dream Survey               harris_youth_2011:17632   
35694     2011 Memorable Dream Survey                    harris_2011:065725   
36826     2011 Memorable Dream Survey                    harris_2011:027479   
36850     2011 Memorable Dream Survey                    harris_2011:027384   
39213         2010 Demographic Survey                    zogby_052110:40138   
39934         2010 Demographic Survey                    zogby_052110:32317   

              Question Dream Text  
7908           Protest      scary  
17390      Most Recent      "Go."  
21017      Most Recent      scare  
21104      Most Recent      Peace  
21905      Most Recent      nknjj  
24484      Most Recent      noone  
24496      Most Recent      sorry  
25301      Most Recent      nione  
27598       Visitation      None.  
27630        Awareness      None.  
27719             Work      None.  
34415        Memorable      dream  
34465        Memorable      Ummmm  
35062        Memorable      hello  
35694        Memorable      hgefh  
36826        Memorable      GREEN  
36850        Memorable      .....  
39213  Worst Nightmare      dying  
39934  Worst Nightmare      Dying

Ummmm

Back to words, let's look at a subset of 2-word reports.

In [51]:
display(df[df["Dream Text"].str.split().str.len().eq(2)])

Survey Name      Participant ID         Question  \
325                melvin-dreams              Melvin     Last Night's   
329                melvin-dreams              Melvin     Last Night's   
330                melvin-dreams              Melvin     Last Night's   
333                melvin-dreams              Melvin     Last Night's   
339                melvin-dreams              Melvin     Last Night's   
...                          ...                 ...              ...   
41155    2010 Demographic Survey  zogby_052110:12680  Worst Nightmare   
41244    2010 Demographic Survey   zogby_052110:9627  Worst Nightmare   
41249    2010 Demographic Survey   zogby_052110:9504      Most Recent   
41398    2010 Demographic Survey   zogby_052110:3694  Worst Nightmare   
43983  Lucille Journal 1998-2018             Lucille     Last Night's   

                     Dream Text  
325                  William B.  
329                    David L.  
330                   Joseph I.  
333            several Italic's  
339                Patos Island  
...                         ...  
41155               No response  
41244           See previous...  
41249              work related  
41398              being chased  
43983  Seattle-like place/hotel  

[613 rows x 4 columns]

Definitely have to keep some of these, but also stuff like No response could come out. Even trickier is "See previous..." - I don't think it's worth extracting their previous response and placing it there...

#### Removing

I want to remove some of these no-report reports before checking for duplicates, as they will definitely muck up the duplicate counts.

Generate a custom list of phrases relating to no response that have been observed in the dataset.

In [52]:
NO_REPORT_PATTERNS = [
    r"\S?n+o+\S*",  # This one catches almost everything (see previous cell output)
    r"(i )?((do|ca)(n'?t| not)|no) (remember|recall|know|dream)( my)?( dream)?\S*",  # don't remember, I don't recall., I do not recall, i dont know
    r"\.\s?\S*",  # ., ..., ....., ...no., .pop, ". ,nlmbhv"
    r"no(t|ne|pe|thing)?\S?(\s+\S+){,50}",  # No - I don't recall anything like that., nothing off the top of my head.
    r"[ui]nknown",  # unknown, UNKNOWN, inknown
    r"\S?nothing\S?",  # nothing, Nothing, Nothing!
    r"\S?yes\S*",  # yes, yes., yes/no
    r"\S?n\S?a\S?",  # n.a, na, naa, nah, naw, N/A.
    r".{1,2}",  # One or two character sequences, like f, g, 4, ., ?, ??, -, etc.
    r"(\S)\1+",  # repeated characters like Gggg, Zzz, mmmmmmm, and one entry that is just 207 x's
    r"I have",
    r"I don't have nightmares\.",
    r"Refused",
    r"I don't remember any of my dreams\.",
    r"i don't really remember my dreams",
    r"I don't recall any at this time\.",
    r"Can't remember now",
    r"Can't remember any",
    r"Can't remember any\.",
    r"Can't think of one\.",
    r"Cannot remember",
    r"Don't remember any",
    r"pass",
    r"private",
    r"personal",
    r"rather not",
    r"same",
    r"unsure",
    r"yes, don't care to",
    r"yes but I don't remember any details any more",
    
]

Display some of the concerns by showing the counts for different matches in the first 3 patterns.

In [53]:
display(
    df[df["Dream Text"].str.fullmatch(NO_REPORT_PATTERNS[0], flags=re.IGNORECASE)]["Dream Text"]
    .value_counts()
    .sort_index(key=lambda s: s.str.lower())
    .to_frame()
)

count
Dream Text       
"None"         10
"none"          6
NNone           1
no            461
No            118
NO             24
No!!            1
No.            18
no.             3
noe             1
Nome            1
nome            1
none         2644
NONe            1
NOne            3
nONE            2
NONE           87
none"           1
none.           3
None.          31
NONO            1
Nono            1
nonw            1
nonwe           1
noone           1
noooooooo       1
Nope            4
nope            8
Nope.           1
not             1
Nothing         4
nothing        21
Nothing!        1
NOYB            1

In [54]:
display(
    df[df["Dream Text"].str.fullmatch(NO_REPORT_PATTERNS[1], flags=re.IGNORECASE)]["Dream Text"]
    .value_counts()
    .sort_index(key=lambda s: s.str.lower())
    .to_frame()
)

count
Dream Text                      
can't recall                   3
Can't recall                   3
can't remember                38
Can't remember                22
Can't Remember                 1
...                          ...
i dont remember my dreams      3
No dream                       1
no dream                       2
no dreams                     10
no recall                      1

[126 rows x 1 columns]

In [55]:
display(
    df[df["Dream Text"].str.fullmatch(NO_REPORT_PATTERNS[2], flags=re.IGNORECASE)]["Dream Text"]
    .value_counts()
    .sort_index(key=lambda s: s.str.lower())
    .to_frame()
)

count
Dream Text           
.                  21
. ,nlmbhv           1
...                 2
....                2
.....               1
.......             1
..............      1
...no               1
.pop                1

In [56]:
# Remove rows that match patterns
n_rows_before = df.shape[0]
print("Number of rows before non-response corrections:", n_rows_before)
for pattern in NO_REPORT_PATTERNS:
    n_before = df["Dream Text"].str.fullmatch(pattern, flags=re.IGNORECASE).sum()
    df = df[~df["Dream Text"].str.fullmatch(pattern, flags=re.IGNORECASE)]
    n_after = df["Dream Text"].str.fullmatch(pattern, flags=re.IGNORECASE).sum()
    print(f"Number of dream {pattern} matches before/after correction: {n_before}/{n_after}")
n_rows_after = df.shape[0]
print("Number of rows after non-response corrections:", n_rows_after)
print("Number of rows removed:", n_rows_before - n_rows_after)

Number of rows before non-response corrections: 42989
Number of dream \S?n+o+\S* matches before/after correction: 3464/0
Number of dream (i )?((do|ca)(n'?t| not)|no) (remember|recall|know|dream)( my)?( dream)?\S* matches before/after correction: 560/0
Number of dream \.\s?\S* matches before/after correction: 31/0
Number of dream no(t|ne|pe|thing)?\S?(\s+\S+){,50} matches before/after correction: 342/0
Number of dream [ui]nknown matches before/after correction: 3/0
Number of dream \S?nothing\S? matches before/after correction: 0/0
Number of dream \S?yes\S* matches before/after correction: 116/0
Number of dream \S?n\S?a\S? matches before/after correction: 193/0
Number of dream .{1,2} matches before/after correction: 69/0
Number of dream (\S)\1+ matches before/after correction: 30/0
Number of dream I have matches before/after correction: 3/0
Number of dream I don't have nightmares\. matches before/after correction: 2/0
Number of dream Refused matches before/after correction: 3/0
Number of

In [57]:
# Display the description of DataFrame at this point
display(df.describe(include="all"))

Survey Name Participant ID      Question Dream Text
count                38097          38097         38097      38097
unique                  85          13240            21      37528
top     Online Dreams 2015         Melvin  Last Night's     flying
freq                  5903           5200         22346         11

Flying is now the most common Dream Text value, that makes more realistic sense!

More non-response issues.

These two political ones I noticed are particularly odd since they aren't even in the Obama dataset...? But they _are_ from the same participant...

In [58]:
df.loc[df["Participant ID"].eq("zogby_052110:11536")]

Survey Name      Participant ID         Question  \
41183  2010 Demographic Survey  zogby_052110:11536      Most Recent   
41190  2010 Demographic Survey  zogby_052110:11536  Worst Nightmare   

                                              Dream Text  
41183                             Obama lost in 2012! :)  
41190  Obamacare showed its true colors of sky rocket...

In [59]:
print("Full dream (index 41183):", df.loc[df["Participant ID"].eq("zogby_052110:11536")].loc[41183, "Dream Text"])
print("Full dream (index 41190):", df.loc[df["Participant ID"].eq("zogby_052110:11536")].loc[41190, "Dream Text"])

Full dream (index 41183): Obama lost in 2012! :)
Full dream (index 41190): Obamacare showed its true colors of sky rocketing taxes and dwindling service after the 2012 elections.


We can remove this participant.

In [60]:
df = df.loc[~df["Participant ID"].eq("zogby_052110:11536")]

### Investigate duplicate rows

In my experience duplicate row checking can reveal a lot about issues with a dataset. Also a lot of the issues are difficult to directly address.

We probably got rid of a lot of duplicates by removing the non-responses earlier. Those are typically the biggest issue for duplicates.

We will go in this order:

* Second, check rows that are duplicated in subsets of columns. For example, They dream reports are the same but the Question is different.

First, check rows that are duplicated _entirely_ across all columns. There's an easy solution there: remove them.

In [61]:
n_duplicated_rows = df.duplicated().sum()
print("Number of duplicated rows:", n_duplicated_rows)

Number of duplicated rows: 35


Show which datasets are contributing duplicates

In [62]:
display(df[df.duplicated()]["Survey Name"].value_counts().reset_index(name="n_duplicates"))

Survey Name  n_duplicates
0      Online Dreams 2015            27
1  Anthropological Dreams             3
2           melvin-dreams             2
3       Tita Journal 2020             1
4   Magnolia Journal 2015             1
5    Jordan Dream Journal             1

Show the full dataframe of duplicates, including the duplicated rows for clarity.

In [63]:
display(df[df.duplicated(keep=False)])

Survey Name          Participant ID      Question  \
328            melvin-dreams                  Melvin  Last Night's   
363            melvin-dreams                  Melvin  Last Night's   
396            melvin-dreams                  Melvin  Last Night's   
8943       Tita Journal 2020                    Tita  Last Night's   
8998       Tita Journal 2020                    Tita  Last Night's   
...                      ...                     ...           ...   
17129     Online Dreams 2015  recent_dreams_2015:759  Last Night's   
17614  Magnolia Journal 2015      magnolia1:magnolia  Last Night's   
17625  Magnolia Journal 2015      magnolia1:magnolia  Last Night's   
18843   Jordan Dream Journal    jordan_series:jordan  Last Night's   
18844   Jordan Dream Journal    jordan_series:jordan  Last Night's   

                                              Dream Text  
328                                                 Mary  
363                                                 Mary  
396                                                 Mary  
8943   I was redecorating my mother’s room. The paint...  
8998   I was redecorating my mother’s room. The paint...  
...                                                  ...  
17129  I think I was in a memory of the past. Was on ...  
17614  “Durango”  I went with Evan and Jim to get cof...  
17625  “Durango”  I went with Evan and Jim to get cof...  
18843  I had another dream. Made a big impression on ...  
18844  I had another dream. Made a big impression on ...  

[66 rows x 4 columns]

Show a more informative view that provides a count of how many duplicates there are for each duplicated row.

In [64]:
display(
    df
    .groupby(["Survey Name", "Participant ID", "Question", "Dream Text"])
    .size()
    .reset_index(name="count")
    .sort_values(["count", "Survey Name"], ascending=[False, True])
    .query("count > 1")
)

Survey Name                          Participant ID  \
12626  Anthropological Dreams  anthropological_dreams:barbara_tedlock   
27647      Online Dreams 2015                recent_dreams_2015:55336   
36334           melvin-dreams                                  Melvin   
17475    Jordan Dream Journal                    jordan_series:jordan   
21757   Magnolia Journal 2015                      magnolia1:magnolia   
25136      Online Dreams 2015                recent_dreams_2015:22067   
25531      Online Dreams 2015                recent_dreams_2015:24962   
27623      Online Dreams 2015                recent_dreams_2015:55336   
27773      Online Dreams 2015                 recent_dreams_2015:5592   
27930      Online Dreams 2015                recent_dreams_2015:56465   
28465      Online Dreams 2015                recent_dreams_2015:63471   
29402      Online Dreams 2015                  recent_dreams_2015:759   
29403      Online Dreams 2015                  recent_dreams_2015:759   
29404      Online Dreams 2015                  recent_dreams_2015:759   
29405      Online Dreams 2015                  recent_dreams_2015:759   
29407      Online Dreams 2015                  recent_dreams_2015:759   
29408      Online Dreams 2015                  recent_dreams_2015:759   
29413      Online Dreams 2015                  recent_dreams_2015:759   
29414      Online Dreams 2015                  recent_dreams_2015:759   
29416      Online Dreams 2015                  recent_dreams_2015:759   
29418      Online Dreams 2015                  recent_dreams_2015:759   
29419      Online Dreams 2015                  recent_dreams_2015:759   
29420      Online Dreams 2015                  recent_dreams_2015:759   
29421      Online Dreams 2015                  recent_dreams_2015:759   
29425      Online Dreams 2015                  recent_dreams_2015:759   
29427      Online Dreams 2015                  recent_dreams_2015:759   
29430      Online Dreams 2015                  recent_dreams_2015:759   
29431      Online Dreams 2015                  recent_dreams_2015:759   
29433      Online Dreams 2015                  recent_dreams_2015:759   
29434      Online Dreams 2015                  recent_dreams_2015:759   
32263       Tita Journal 2020                                    Tita   

           Question                                         Dream Text  count  
12626     Memorable  Twenty days into our apprenticeship I dreamedâ...      4  
27647  Last Night's  Remember a few dream states but the only other...      3  
36334  Last Night's                                               Mary      3  
17475  Last Night's  I had another dream. Made a big impression on ...      2  
21757  Last Night's  “Durango”  I went with Evan and Jim to get cof...      2  
25136  Last Night's  I was at a party at college, where for some re...      2  
25531  Last Night's  Was going over to Ricky's house, which was on ...      2  
27623  Last Night's  - wing commander style dream. One where it was...      2  
27773  Last Night's  I was standing outside talking about wanting t...      2  
27930  Last Night's  I am on a walk with Alex in Albania. Or was it...      2  
28465  Last Night's  ... I am at work in building B cleaning out so...      2  
29402  Last Night's  A group of people had to traverse across a vas...      2  
29403  Last Night's  At the beach in Oct, weird but my family did t...      2  
29404  Last Night's  Driving on north 202, around where East Amwell...      2  
29405  Last Night's  English class that looked like 7th grade LA cl...      2  
29407  Last Night's  I had just got home, went in the master bathro...      2  
29408  Last Night's  I think I was in a memory of the past. Was on ...      2  
29413  Last Night's  I was sitting on a bench with Mike. Some guy c...      2  
29414  Last Night's  I was trying to date Kelly (haven't talked to ...      2  
29416  Last Night's  In Barley Sheaf but everything was different f...      2  
2

4 copies of the same row in the "Anthropological Dreams" dataset!

I think these can all be removed, except maybe the Melvin dataset duplicate, since it's just "Mary" and that seems feasible to appear twice. The others are too long and detailed to be true duplicates.

In [65]:
display(df[df.duplicated(keep=False)].query("`Survey Name` == 'melvin-dreams'"))

Survey Name Participant ID      Question Dream Text
328  melvin-dreams         Melvin  Last Night's       Mary
363  melvin-dreams         Melvin  Last Night's       Mary
396  melvin-dreams         Melvin  Last Night's       Mary

In [66]:
display(df[df["Dream Text"].str.split().str.len().eq(1)].query("`Survey Name` == 'melvin-dreams'"))

Survey Name Participant ID      Question Dream Text
328   melvin-dreams         Melvin  Last Night's       Mary
340   melvin-dreams         Melvin  Last Night's    Seattle
363   melvin-dreams         Melvin  Last Night's       Mary
377   melvin-dreams         Melvin  Last Night's    Flying?
396   melvin-dreams         Melvin  Last Night's       Mary
2684  melvin-dreams         Melvin  Last Night's       Mom.
3336  melvin-dreams         Melvin  Last Night's     Carol.

Since Melvin has a few other 1-word name dreams, we can keep his. But drop all other duplicate rows.

In [67]:
non_duplicate_index = df.drop_duplicates(keep="first").index
melvin_dreams_index = df.loc[df["Survey Name"] == "melvin-dreams"].index
df = df.loc[non_duplicate_index.union(melvin_dreams_index)]
display(df[df.duplicated(keep=False)])

Survey Name Participant ID      Question Dream Text
328  melvin-dreams         Melvin  Last Night's       Mary
363  melvin-dreams         Melvin  Last Night's       Mary
396  melvin-dreams         Melvin  Last Night's       Mary

Full-row duplicates are taken care of. Now look at potential duplicates outside of Question column. That is, duplicate reports from the same participant in the same dataset, but with different question values. Like if a participant put the same dream report for different responses.

I suppose this is plausible to keep, for example if someone reported the same dream for their "most memorable" and their "worst nightmare".

In [68]:
subset = ["Survey Name", "Participant ID", "Dream Text"]
n_duplicates = df.duplicated(subset=subset).sum()
print("Number of duplicated rows (subset):", n_duplicates)

Number of duplicated rows (subset): 192


In [69]:
display(df[df.duplicated(subset=subset, keep=False)].sort_values(by=subset))

Survey Name      Participant ID             Question  \
41055  2010 Demographic Survey  zogby_052110:15540  Earliest Remembered   
41060  2010 Demographic Survey  zogby_052110:15540      Worst Nightmare   
40921  2010 Demographic Survey  zogby_052110:19255  Earliest Remembered   
40929  2010 Demographic Survey  zogby_052110:19255      Worst Nightmare   
40856  2010 Demographic Survey  zogby_052110:20758  Earliest Remembered   
...                        ...                 ...                  ...   
17892        Nepal Dreams 2014  nepaldreams:yuwa_s          Significant   
17916        Nepal Dreams 2014  nepaldreams:yuwa_s            Spiritual   
328              melvin-dreams              Melvin         Last Night's   
363              melvin-dreams              Melvin         Last Night's   
396              melvin-dreams              Melvin         Last Night's   

                                              Dream Text  
41055  I was being attacked by Walt Disney characters...  
41060  I was being attacked by Walt Disney characters...  
40921  sliding down dark stairway to basement in chil...  
40929  sliding down dark stairway to basement in chil...  
40856  Falling in the deep ocean, seeing pretty tropi...  
...                                                  ...  
17892  [During the day I rebuked a demon. That night ...  
17916  [During the day I rebuked a demon. That night ...  
328                                                 Mary  
363                                                 Mary  
396                                                 Mary  

[372 rows x 4 columns]

Indeed, it looks at a glance like there are certain datasets where - while less than ideal - this is an acceptable response pattern and should stay.

Now, look for duplicates that are _not_ from the same participant. We look at a subset of only "Survey NAme" and "Dream Text". This would be more concerning, as any detailed dream is highly unlikely to be reported identically between two different participants.

In [70]:
subset = ["Survey Name", "Dream Text"]
# Just for viewing, drop the duplicates that are from the same Participant ID.
# We are keeping them for the output, but need to remove them for viewing this other case.
no_participant_dups = df.drop_duplicates(subset=["Survey Name", "Participant ID", "Dream Text"])
display(
    no_participant_dups[no_participant_dups.duplicated(subset=subset, keep=False)]
    .sort_values(by=subset)
)

Survey Name            Participant ID  \
38725                      2010 Demographic Survey        zogby_052110:45077   
39588                      2010 Demographic Survey        zogby_052110:36276   
39611                      2010 Demographic Survey        zogby_052110:35945   
40375                      2010 Demographic Survey        zogby_052110:27726   
39552                      2010 Demographic Survey        zogby_052110:36456   
...                                            ...                       ...   
20081  Krippner International Collection 1990-2005  krippner_survey1:kbrazf3   
20304  Krippner International Collection 1990-2005  krippner_survey1:kargf51   
20305  Krippner International Collection 1990-2005  krippner_survey1:kargf52   
20292  Krippner International Collection 1990-2005  krippner_survey1:kargf39   
20293  Krippner International Collection 1990-2005  krippner_survey1:kargf40   

                  Question                                         Dream Text  
38725  Earliest Remembered                                       Being chased  
39588      Worst Nightmare                                       Being chased  
39611  Earliest Remembered                                       Being chased  
40375      Worst Nightmare                                       Being chased  
39552  Earliest Remembered                                            Falling  
...                    ...                                                ...  
20081          Most Recent  I was going down a road, and I saw someone. I ...  
20304          Most Recent  I was on a huge bed. I knew that on one side w...  
20305          Most Recent  I was on a huge bed. I knew that on one side w...  
20292          Most Recent  My mother (who actually had killed herself som...  
20293          Most Recent  My mother (who actually had killed herself som...  

[194 rows x 4 columns]

This is definitely problematic, as there should not be **lengthy** dream reports that are the same across participants. Duplicates of "Falling" is okay, but not the longer reports, for example in the Krippner dataset.

In [71]:
(
    no_participant_dups[no_participant_dups.duplicated(subset=subset, keep=False)].sort_values(by=subset)
    .query("`Survey Name` == 'Krippner International Collection 1990-2005'")
    .drop(columns=["Question"])
)

Survey Name  \
20110  Krippner International Collection 1990-2005   
20111  Krippner International Collection 1990-2005   
20055  Krippner International Collection 1990-2005   
20056  Krippner International Collection 1990-2005   
20204  Krippner International Collection 1990-2005   
20205  Krippner International Collection 1990-2005   
20215  Krippner International Collection 1990-2005   
20216  Krippner International Collection 1990-2005   
20403  Krippner International Collection 1990-2005   
20404  Krippner International Collection 1990-2005   
20078  Krippner International Collection 1990-2005   
20081  Krippner International Collection 1990-2005   
20304  Krippner International Collection 1990-2005   
20305  Krippner International Collection 1990-2005   
20292  Krippner International Collection 1990-2005   
20293  Krippner International Collection 1990-2005   

                   Participant ID  \
20110   krippner_survey1:kbrazf32   
20111   krippner_survey1:kbrazf33   
20055  krippner_survey1:kbrazf114   
20056  krippner_survey1:kbrazf115   
20204    krippner_survey1:kargm54   
20205    krippner_survey1:kargm55   
20215    krippner_survey1:kargm65   
20216    krippner_survey1:kargm66   
20403    krippner_survey1:kjapf43   
20404    krippner_survey1:kjapf44   
20078  krippner_survey1:kbrazf137   
20081    krippner_survey1:kbrazf3   
20304    krippner_survey1:kargf51   
20305    krippner_survey1:kargf52   
20292    krippner_survey1:kargf39   
20293    krippner_survey1:kargf40   

                                              Dream Text  
20110  I am in a civilization in a place that is the ...  
20111  I am in a civilization in a place that is the ...  
20055  I am in a large auditorium attending a class o...  
20056  I am in a large auditorium attending a class o...  
20204  I saw some enormous birds, but I only recall t...  
20205  I saw some enormous birds, but I only recall t...  
20215  I was chatting with my brother in the living r...  
20216  I was chatting with my brother in the living r...  
20403  I was dreaming that I had fallen ill. I was in...  
20404  I was dreaming that I had fallen ill. I was in...  
20078  I was going down a road, and I saw someone. I ...  
20081  I was going down a road, and I saw someone. I ...  
20304  I was on a huge bed. I knew that on one side w...  
20305  I was on a huge bed. I knew that on one side w...  
20292  My mother (who actually had killed herself som...  
20293  My mother (who actually had killed herself som...

For a better perspective on these issues, view the duplicates from dream reports less than 30 characters and more than 30 characters separately.

In [72]:
(
    no_participant_dups[no_participant_dups.duplicated(subset=subset, keep=False)]
    .sort_values(by=subset)
    .drop(columns=["Question"])
    .query("`Dream Text`.str.len() < 30")
)

Survey Name         Participant ID    Dream Text
38725    2010 Demographic Survey     zogby_052110:45077  Being chased
39588    2010 Demographic Survey     zogby_052110:36276  Being chased
39611    2010 Demographic Survey     zogby_052110:35945  Being chased
40375    2010 Demographic Survey     zogby_052110:27726  Being chased
39552    2010 Demographic Survey     zogby_052110:36456       Falling
...                          ...                    ...           ...
5647   2021 Sports Dreams Survey  sportsDreams2021:2622    Basketball
5684   2021 Sports Dreams Survey  sportsDreams2021:1509    Basketball
5693   2021 Sports Dreams Survey  sportsDreams2021:4674    Basketball
5530   2021 Sports Dreams Survey  sportsDreams2021:3370      Football
5633   2021 Sports Dreams Survey  sportsDreams2021:3561      Football

[159 rows x 3 columns]

In [73]:
with pd.option_context("display.max_rows", None):
    display(
        no_participant_dups[no_participant_dups.duplicated(subset=subset, keep=False)]
        .sort_values(by=subset)
        # .drop(columns=["Question"])
        .query("`Dream Text`.str.len() < 30")
    )

Survey Name           Participant ID  \
38725         2010 Demographic Survey       zogby_052110:45077   
39588         2010 Demographic Survey       zogby_052110:36276   
39611         2010 Demographic Survey       zogby_052110:35945   
40375         2010 Demographic Survey       zogby_052110:27726   
39552         2010 Demographic Survey       zogby_052110:36456   
39852         2010 Demographic Survey       zogby_052110:33061   
40558         2010 Demographic Survey       zogby_052110:25685   
40857         2010 Demographic Survey       zogby_052110:20626   
41465         2010 Demographic Survey        zogby_052110:1310   
39940         2010 Demographic Survey       zogby_052110:32231   
40035         2010 Demographic Survey       zogby_052110:31342   
41381         2010 Demographic Survey        zogby_052110:4029   
39233         2010 Demographic Survey       zogby_052110:40046   
40898         2010 Demographic Survey       zogby_052110:20101   
39188         2010 Demographic Survey       zogby_052110:40534   
40676         2010 Demographic Survey       zogby_052110:24568   
39223         2010 Demographic Survey       zogby_052110:40089   
39629         2010 Demographic Survey       zogby_052110:35856   
38703         2010 Demographic Survey       zogby_052110:45212   
41000         2010 Demographic Survey       zogby_052110:17008   
41398         2010 Demographic Survey        zogby_052110:3694   
38404         2010 Demographic Survey       zogby_052110:49102   
38737         2010 Demographic Survey       zogby_052110:44880   
40662         2010 Demographic Survey       zogby_052110:24739   
38440         2010 Demographic Survey       zogby_052110:48824   
38865         2010 Demographic Survey       zogby_052110:43563   
39655         2010 Demographic Survey       zogby_052110:35411   
39800         2010 Demographic Survey       zogby_052110:33813   
39882         2010 Demographic Survey       zogby_052110:32808   
38369         2010 Demographic Survey       zogby_052110:49427   
38376         2010 Demographic Survey       zogby_052110:49220   
38735         2010 Demographic Survey       zogby_052110:44880   
38986         2010 Demographic Survey       zogby_052110:42509   
40657         2010 Demographic Survey       zogby_052110:24739   
41078         2010 Demographic Survey       zogby_052110:14890   
34715    2011 Children's Dream Survey   harris_youth_2011:7827   
35299    2011 Children's Dream Survey  harris_youth_2011:36340   
35008    2011 Children's Dream Survey  harris_youth_2011:20356   
35410    2011 Children's Dream Survey  harris_youth_2011:43787   
34693    2011 Children's Dream Survey   harris_youth_2011:8958   
34820    2011 Children's Dream Survey  harris_youth_2011:14855   
35091    2011 Children's Dream Survey  harris_youth_2011:28745   
35417    2011 Children's Dream Survey  harris_youth_2011:43713   
35579    2011 Children's Dream Survey  harris_youth_2011:44890   
35509    2011 Children's Dream Survey  harris_youth_2011:61399   
35515    2011 Children's Dream Survey  harris_youth_2011:53624   
34645    2011 Children's Dream Survey  harris_youth_2011:10202   
34807    2011 Children's Dream Survey  harris_youth_2011:15223   
34972    2011 Children's Dream Survey  harris_youth_2011:21941   
34459    2011 Children's Dream Survey   harris_youth_2011:1689   
35590    2011 Children's Dream Survey  harris_youth_2011:44265   
35037    2011 Children's Dream Survey  harris_youth_2011:19260   
35214    2011 Children's Dream Survey  harris_youth_2011:23670   
35130    2011 Children's Dream Survey  harris_youth_2011:25987   
35142    2011 Children's Dream Survey  harris_youth_2011:25740   
34551    2011 Children's Dream Survey   harris_youth_2011:4527   
34856    2011 Children's Dream Survey  harris_youth_2011:13595   
34552    2011 Children's Dream Survey   harris_youth_2011:4519   
35154    2011 Children's Dream Survey  harris_youth_2011:25267   
34484    2011 Children's Dream Survey   harris_youth_2011:1070   


This full view helps to see a lot more non-response issues that could've gotten pulled out earlier.

In [74]:
(
    no_participant_dups[no_participant_dups.duplicated(subset=subset, keep=False)]
    .sort_values(by=subset)
    .drop(columns=["Question"])
    .query("`Dream Text`.str.len() >= 30")
)

Survey Name  \
5564                     2021 Sports Dreams Survey   
5749                     2021 Sports Dreams Survey   
5790                     2021 Sports Dreams Survey   
18643                   Dreamboard Nightmares 2014   
18644                   Dreamboard Nightmares 2014   
18268                   Dreamboard Nightmares 2014   
18269                   Dreamboard Nightmares 2014   
18264                   Dreamboard Nightmares 2014   
18265                   Dreamboard Nightmares 2014   
18295                   Dreamboard Nightmares 2014   
18296                   Dreamboard Nightmares 2014   
18262                   Dreamboard Nightmares 2014   
18263                   Dreamboard Nightmares 2014   
18349                   Dreamboard Nightmares 2014   
18350                   Dreamboard Nightmares 2014   
18292                   Dreamboard Nightmares 2014   
18293                   Dreamboard Nightmares 2014   
18618                   Dreamboard Nightmares 2014   
18619                   Dreamboard Nightmares 2014   
20110  Krippner International Collection 1990-2005   
20111  Krippner International Collection 1990-2005   
20055  Krippner International Collection 1990-2005   
20056  Krippner International Collection 1990-2005   
20204  Krippner International Collection 1990-2005   
20205  Krippner International Collection 1990-2005   
20215  Krippner International Collection 1990-2005   
20216  Krippner International Collection 1990-2005   
20403  Krippner International Collection 1990-2005   
20404  Krippner International Collection 1990-2005   
20078  Krippner International Collection 1990-2005   
20081  Krippner International Collection 1990-2005   
20304  Krippner International Collection 1990-2005   
20305  Krippner International Collection 1990-2005   
20292  Krippner International Collection 1990-2005   
20293  Krippner International Collection 1990-2005   

                   Participant ID  \
5564        sportsDreams2021:2980   
5749        sportsDreams2021:2981   
5790        sportsDreams2021:2979   
18643   dreamboarda:dreamboarda50   
18644   dreamboarda:dreamboarda51   
18268  dreamboarda:dreamboarda359   
18269  dreamboarda:dreamboarda360   
18264  dreamboarda:dreamboarda355   
18265  dreamboarda:dreamboarda356   
18295  dreamboarda:dreamboarda386   
18296  dreamboarda:dreamboarda387   
18262  dreamboarda:dreamboarda353   
18263  dreamboarda:dreamboarda354   
18349  dreamboarda:dreamboarda440   
18350  dreamboarda:dreamboarda441   
18292  dreamboarda:dreamboarda383   
18293  dreamboarda:dreamboarda384   
18618  dreamboarda:dreamboarda187   
18619  dreamboarda:dreamboarda188   
20110   krippner_survey1:kbrazf32   
20111   krippner_survey1:kbrazf33   
20055  krippner_survey1:kbrazf114   
20056  krippner_survey1:kbrazf115   
20204    krippner_survey1:kargm54   
20205    krippner_survey1:kargm55   
20215    krippner_survey1:kargm65   
20216    krippner_survey1:kargm66   
20403    krippner_survey1:kjapf43   
20404    krippner_survey1:kjapf44   
20078  krippner_survey1:kbrazf137   
20081    krippner_survey1:kbrazf3   
20304    krippner_survey1:kargf51   
20305    krippner_survey1:kargf52   
20292    krippner_survey1:kargf39   
20293    krippner_survey1:kargf40   

                                              Dream Text  
5564                  I often dream of playing badminton  
5749                  I often dream of playing badminton  
5790                  I often dream of playing badminton  
18643  *Translated from French* I go alone at night I...  
18644  *Translated from French* I go alone at night I...  
18268  I saw my left eye has something like jerry sti...  
18269  I saw my left eye has something like jerry sti...  
18264  I was in a hospital of sorts.  My room went to...  
18265  I was in a hospital of sorts.  My room went to...  
18295  I was in bed and my son Mason was in his crib ...  
18296  I was in bed and my son Mason was in his crib ...  
18262  I was in this random place and Optimus and Meg

Another level down

In [75]:
no_id_dups = no_participant_dups.drop_duplicates(subset=subset)

In [76]:
subset = ["Survey Name", "Dream Text"]
assert not no_id_dups.duplicated(subset=subset).any()

Still definitely going to be a lot of duplicated dream reports. Probably worth looking at thos with relatively low character counts, since it revealed a lot before, but we still haven't seen this without any other columns involved.

In [77]:
with pd.option_context("display.min_rows", 100):
    display(
        df[df.duplicated(subset=["Dream Text"], keep=False)]
        .query("`Dream Text`.str.len() < 20")
        .sort_values(by=["Dream Text", "Survey Name", "Participant ID", "Question"])
    )

Survey Name           Participant ID  \
5684        2021 Sports Dreams Survey    sportsDreams2021:1509   
5647        2021 Sports Dreams Survey    sportsDreams2021:2622   
5693        2021 Sports Dreams Survey    sportsDreams2021:4674   
40375         2010 Demographic Survey       zogby_052110:27726   
39611         2010 Demographic Survey       zogby_052110:35945   
39588         2010 Demographic Survey       zogby_052110:36276   
38725         2010 Demographic Survey       zogby_052110:45077   
7927       2020 Racial Justice Survey   2020racialjustice:1029   
35570    2011 Children's Dream Survey  harris_youth_2011:45915   
35736     2011 Memorable Dream Survey       harris_2011:063940   
41465         2010 Demographic Survey        zogby_052110:1310   
40857         2010 Demographic Survey       zogby_052110:20626   
40558         2010 Demographic Survey       zogby_052110:25685   
39852         2010 Demographic Survey       zogby_052110:33061   
39552         2010 Demographic Survey       zogby_052110:36456   
40433         2010 Demographic Survey       zogby_052110:26886   
21942  2013 Demographic Survey Summer      harris_2013s:002189   
40035         2010 Demographic Survey       zogby_052110:31342   
39940         2010 Demographic Survey       zogby_052110:32231   
41381         2010 Demographic Survey        zogby_052110:4029   
5530        2021 Sports Dreams Survey    sportsDreams2021:3370   
5633        2021 Sports Dreams Survey    sportsDreams2021:3561   
21565  2013 Demographic Survey Summer      harris_2013s:002675   
25542  2013 Demographic Survey Winter      harris_2013w:005624   
38569         2010 Demographic Survey       zogby_052110:47006   
8163         2020 Pandemic May Survey  2020pandemicsurvey:2588   
35142    2011 Children's Dream Survey  harris_youth_2011:25740   
35130    2011 Children's Dream Survey  harris_youth_2011:25987   
25765  2013 Demographic Survey Winter      harris_2013w:005869   
5477        2021 Sports Dreams Survey    sportsDreams2021:2419   
...                               ...                      ...   
36568     2011 Memorable Dream Survey       harris_2011:030437   
35000    2011 Children's Dream Survey  harris_youth_2011:20733   
35684     2011 Memorable Dream Survey       harris_2011:067250   
35551    2011 Children's Dream Survey  harris_youth_2011:48947   
35833     2011 Memorable Dream Survey       harris_2011:052509   
21455  2013 Demographic Survey Summer      harris_2013s:002798   
25382  2013 Demographic Survey Winter      harris_2013w:005429   
8358         2020 Pandemic May Survey    2020pandemicsurvey:85   
7808       2020 Racial Justice Survey   2020racialjustice:3700   
28684         2012 Demographic Survey       harris_2012:001497   
29689         2012 Demographic Survey       harris_2012:001914   
30407         2012 Demographic Survey       harris_2012:002189   
31342         2012 Demographic Survey       harris_2012:002554   
31340         2012 Demographic Survey       harris_2012:002554   
32278         2012 Demographic Survey       harris_2012:002905   
34001         2012 Demographic Survey       harris_2012:003569   
38582         2010 Demographic Survey       zogby_052110:46925   
36973     2011 Memorable Dream Survey       harris_2011:017337   
22312  2013 Demographic Survey Summer      harris_2013s:001732   
25514  2013 Demographic Survey Winter      harris_2013w:005593   
8266         2020 Pandemic May Survey  2020pandemicsurvey:1415   
33998         2012 Demographic Survey       harris_2012:003568   
21017  2013 Demographic Survey Summer      harris_2013s:003345   
28026         2012 Demographic Survey       harris_2012:001243   
28027         2012 Demographic Survey       harris_2012:001243   
28025         2012 Demographic Survey       harris_2012:001243   
22279  2013 Demographic Survey Summer      harris_2013s:001788   
21183  2013 Demographic Survey Summer      harris_2013s:003130   
33202         2012 Demographic Survey       harris_2012:003254   


## Clean dream reports

These steps are **not** extensive and any downstream analyses of this data should take additional steps of data inspection and cleaning.

### Remove spaces surrounding dream text

Dream reports sometimes contain extra spaces before and/or after the text, which only cause confusion and can easily be removed.

In [78]:
# Remove leading and/or trailing whitespace
n_to_strip = (df["Dream Text"].str.strip() != df["Dream Text"]).sum()
print("Number of dreams with leading or trailing whitespace getting corrected:", n_to_strip)
df["Dream Text"] = df["Dream Text"].str.strip()

Number of dreams with leading or trailing whitespace getting corrected: 3869


#### Remove quotes surrounding dream text

Similarly, dream reports sometimes contain quotes surrounding the _entire_ dream text. This also only adds confusing data analysis and can be removed.

In [79]:
# Remove leading AND trailing quotes
# For dream reports that start with a quote and end with a quote, but are **not** one full quote, the quotes should stay
quoted_patterns = [
    r"^“([^“”]+)”$",
    r"^‘([^‘’]+)’$",
    r"^'([^']+)'$",
    r'^"([^"]+)"$',
]

for pattern in quoted_patterns:
    n_before = df["Dream Text"].str.fullmatch(pattern).sum()
    df["Dream Text"] = df["Dream Text"].str.replace(pattern, lambda m: m.group(1), regex=True)
    n_after = df["Dream Text"].str.fullmatch(pattern).sum()
    print(f"Number of {pattern[1]}quoted{pattern[-2]} dreams before/after correction: {n_before}/{n_after}")

Number of “quoted” dreams before/after correction: 6/0
Number of ‘quoted’ dreams before/after correction: 0/0
Number of 'quoted' dreams before/after correction: 36/0
Number of "quoted" dreams before/after correction: 1/0


I think some reports start with "yes," which is probably less dream report and more residue from being a response to a survey question, something like "do you recall a dream from last night"?

In [80]:
df[df["Dream Text"].str.startswith("yes")]

Survey Name           Participant ID     Question  \
7796       2020 Racial Justice Survey   2020racialjustice:3905      Protest   
8192         2020 Pandemic May Survey  2020pandemicsurvey:2258     Pandemic   
22434  2013 Demographic Survey Summer      harris_2013s:001597  Most Recent   
27468         2012 Demographic Survey       harris_2012:001014    Awareness   
27504         2012 Demographic Survey       harris_2012:001029    Awareness   
...                               ...                      ...          ...   
34090         2012 Demographic Survey       harris_2012:003600   Visitation   
34152         2012 Demographic Survey       harris_2012:003629    Awareness   
34161         2012 Demographic Survey       harris_2012:003632    Awareness   
34197         2012 Demographic Survey       harris_2012:003645    Awareness   
34198         2012 Demographic Survey       harris_2012:003645   Visitation   

                                              Dream Text  
7796   yes, but even though it was sort of like the p...  
8192                                        yes hospital  
22434                         yes, horrors of the future  
27468  yes, and it's weird but I make myself change t...  
27504  yes, i have. it's been a while.  it has happen...  
...                                                  ...  
34090                  yes and its none of your business  
34152                     yes many times many situations  
34161  yes.  I was flying using my arms like a birds ...  
34197                                yes fighting aliens  
34198                                         yes my dog  

[277 rows x 4 columns]

In [81]:
print(df.loc[27504, "Dream Text"])

yes, i have. it's been a while.  it has happened several times. it's always a disturbing situation.  so, in my dream, i tell myself, it's just a dream, if i can wake myself up, then i can stop this dream. sometimes i do wake up and, other times, the dream ends and i move on to another dream.


In [82]:
MORE_REMOVAL_PATTERNS = [
    "yes and its none of your business",
    "yes many times many situations",
]
for pattern in MORE_REMOVAL_PATTERNS:
    n_before = df["Dream Text"].str.fullmatch(pattern, flags=re.IGNORECASE).sum()
    df = df[~df["Dream Text"].str.fullmatch(pattern, flags=re.IGNORECASE)]
    n_after = df["Dream Text"].str.fullmatch(pattern, flags=re.IGNORECASE).sum()
    print(f"Number of dream {pattern} matches before/after correction: {n_before}/{n_after}")

Number of dream yes and its none of your business matches before/after correction: 1/0
Number of dream yes many times many situations matches before/after correction: 1/0


In [83]:
df["Dream Text"] = (
    df["Dream Text"]
    .str
    .replace(r"^yes[.,]?\s*", "", regex=True)
)

## Snapshot

In [84]:
df.head()

Survey Name Participant ID      Question  \
0  melvin-dreams         Melvin  Last Night's   
1  melvin-dreams         Melvin  Last Night's   
2  melvin-dreams         Melvin  Last Night's   
3  melvin-dreams         Melvin  Last Night's   
4  melvin-dreams         Melvin  Last Night's   

                                          Dream Text  
0  Mostly forgotten. Flying across an extensive p...  
1  Beginning forgotten. An alternative school cla...  
2  A lot of Mexican, Hispanic, boys. A school sit...  
3  Danny. Before this there was a long bit, mostl...  
4  North side of Queen Sarah Johnson. Not so much...

In [85]:
df.describe(include="all")

Survey Name Participant ID      Question Dream Text
count                38060          38060         38060      38060
unique                  85          13237            21      37521
top     Online Dreams 2015         Melvin  Last Night's     flying
freq                  5876           5200         22316         11

In [86]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
Index: 38060 entries, 0 to 44555
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Survey Name     38060 non-null  object
 1   Participant ID  38060 non-null  object
 2   Question        38060 non-null  object
 3   Dream Text      38060 non-null  object
dtypes: object(4)
memory usage: 43.2 MB


## Tidying

Final tidying-up steps before describing and exporting.

Sort values for clarity.

In [87]:
df = df.sort_values(["Survey Name", "Participant ID", "Question", "Dream Text"])

In [88]:
# Make sure there are no empty cells left after processing
assert not df.isna().any(axis=None)
assert not df.map(len).eq(0).any(axis=None)
assert not df.drop([363, 396]).duplicated().any(axis=None)

## Export

#### Write to file

Save prepared file with compression to save space and ease downloads.

In [89]:
outpath = "./output/sddb.csv.xz"
os.makedirs(os.path.dirname(outpath), exist_ok=True)

TO_CSV_KWARGS = {
    "index": False,
    "na_rep": "N/A",
    "sep": ",",
    "mode": "w",  # Switch to `w` to overwrite existing file
    "encoding": "utf-8-sig",  # Include sig/BOM for better compatibility with Excel
    "compression": "xz",
    "lineterminator": "\n",
    "quoting": 2,  # 2 = csv.QUOTE_NONNUMERIC
    "quotechar": '"',
    "doublequote": True,
}

df.to_csv(outpath, **TO_CSV_KWARGS)

Read it back in and make sure it was not corrupted during output.

In [90]:
assert pd.read_csv(outpath).equals(df.reset_index(drop=True))

In [91]:
print(f"file: {os.path.basename(outpath)}")
print(f"size: {os.path.getsize(outpath) / 1e6} MB")
print(f"md5: {pooch.file_hash(outpath, alg='md5')}")
print(f"sha256: {pooch.file_hash(outpath, alg='sha256')}")
print(f"timestamp: {datetime.fromtimestamp(os.path.getmtime(outpath), tz=timezone.utc).isoformat(timespec='seconds')}")

file: sddb.csv.xz
size: 6.131228 MB
md5: 28b5a11ad5e0ecdcf64c9d32b073396c
sha256: 8cd468c2633c5d9bc955d16d517255d70cef30e3f892b62e8965a6e14d8c3827
timestamp: 2026-01-01T13:20:54+00:00
